shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ['{{ name }}.zsh']
apply = ['defer']

[plugins.zoxide]
inline = 'zsh-defer -c "eval $(zoxide init zsh --cmd cd)"'

[plugins.fzf]
inline = """
export FZF_DEFAULT_OPTS='--height 50% --layout=reverse --border'
zsh-defer -c 'source <(fzf --zsh)'
"""

[plugins.brew]
inline = '''
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi
'''

[plugins.mise]
inline = 'zsh-defer -c "eval $(mise activate zsh)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
